version: '3'
services:
    app:
        image: node:lts
        container_name: app
        links:
            - mongodb
        depends_on:
            - mongodb
        environment:
            - MONGO_URL=mongodb://mongodb/hitachdut
        command: 'bash -c "cd /var/www/ && yarn run web"'
        volumes:
            - .:/var/www
        ports:
            - '3003:3003'
            - '9229:9229'
    mongodb:
        image: mongo:latest
        volumes:
            - ./volumes/mongo:/data/db
        container_name: mongodb
        ports:
            - '27017:27017'
    bot:
        image: golang
        volumes:
            - ../telegram-bot:/go/src/github.com/idoberko2/telegram-bot
        container_name: bot
        depends_on:
            - app
        links:
            - app
        command: 'bash -c "cd /go/src/github.com/idoberko2/telegram-bot && go mod download && go install && /go/bin/telegram-bot"'
