version: '3'
services:
    app:
        image: node:lts
        container_name: app
        links:
            - mongodb
        depends_on:
            - mongodb
        environment:
            - MONGO_URL=mongodb://mongodb
        command: 'bash -c "cd /var/www/ && yarn run web"'
        volumes:
            - .:/var/www
        ports:
            - '3003:3003'
            - '9229:9229'
    mongodb:
        image: mongo:latest
        volumes:
            - ./volumes/mongo:/data/db
        container_name: mongodb
        ports:
            - '27017:27017'
