name: Deploy dokku

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - id: deploy
              name: Deploy to dokku
              uses: idoberko2/dokku-deploy-github-action@leaner-Dockerfile
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  dokku-host: 'idoberko2.com'
                  app-name: 'hitachdut-api'
