name: Deploy dokku

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - id: deploy
              name: Deploy to dokku
              uses: idoberko2/dokku-deploy-github-action@master
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  dokku-host: ${{ secrets.DOKKU_HOST }}
                  app-name: hitachdut-api
