name: Deploy dokku

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                node-version: '12'
            - run: yarn install
            - run: yarn test
            - id: deploy
              name: Deploy to dokku
              uses: idoberko2/dokku-deploy-github-action@v1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  dokku-host: 'idoberko2.com'
                  app-name: 'hitachdut-api'
                  git-push-flags: '--force'
